//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Health_Item
    {
        public Health_Item()
        {
            this.Group_Health_Item = new HashSet<Group_Health_Item>();
            this.Manage_Health = new HashSet<Manage_Health>();
        }
    
        public string HIID { get; set; }
        public string H_Name { get; set; }
        public string H_Comment { get; set; }
    
        public virtual ICollection<Group_Health_Item> Group_Health_Item { get; set; }
        public virtual ICollection<Manage_Health> Manage_Health { get; set; }
    }
}
