//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HealthManageSystemEntities : DbContext
    {
        public HealthManageSystemEntities()
            : base("name=HealthManageSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Group> Group { get; set; }
        public DbSet<Group_Member> Group_Member { get; set; }
        public DbSet<Health_Item> Health_Item { get; set; }
        public DbSet<Login_User> Login_User { get; set; }
        public DbSet<Manage_Health> Manage_Health { get; set; }
        public DbSet<Record> Record { get; set; }
        public DbSet<Remind> Remind { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
