//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remind
    {
        public string REID { get; set; }
        public string UID { get; set; }
        public string RE_Item { get; set; }
        public Nullable<System.TimeSpan> RE_MTime { get; set; }
        public Nullable<System.TimeSpan> RE_ATime { get; set; }
        public Nullable<System.TimeSpan> RE_ETime { get; set; }
        public Nullable<System.TimeSpan> RE_NTime { get; set; }
        public string RE_Monday { get; set; }
        public string RE_Tuesday { get; set; }
        public string RE_Wednesdy { get; set; }
        public string RE_Thursday { get; set; }
        public string RE_Friday { get; set; }
        public string RE_Saturday { get; set; }
        public string RE_Sunday { get; set; }
        public Nullable<int> RE_Repeat { get; set; }
        public string RE_Comment { get; set; }
    
        public virtual Login_User Login_User { get; set; }
    }
}
